import { ValidationReport } from '../types';

export function exportReportToMarkdown(report: ValidationReport): string {
  return `# Startup Validation Report: ${report.ideaInput.title}
**Generated by Evifacto AI** | Date: ${new Date(report.createdAt).toLocaleDateString()}

---

## 1. Executive Recommendation
- **Verdict:** ${report.recommendation}
- **Validation Score:** ${report.validationScore} / 100
- **Confidence Score:** ${report.confidenceScore} / 100
- **Industry:** ${report.ideaInput.industry}
- **Target Audience:** ${report.ideaInput.targetAudience}

### Executive Summary
${report.executiveSummary}

### Domain Name Feasibility
${(report.domainAvailability || [])
  .map((d) => `- **${d.domain}**: ${d.available ? 'AVAILABLE' : 'REGISTERED'}`)
  .join('\n') || '- No domain search records found.'}

---

## 2. Validation Scorecard
- **Market Demand:** ${report.scores.marketDemand}/100
- **Pain Severity:** ${report.scores.painSeverity}/100
- **Tech Feasibility:** ${report.scores.techFeasibility}/100
- **Competition Gap:** ${report.scores.competitionGap}/100
- **Monetization Potential:** ${report.scores.monetizationPotential}/100

---

## 3. Key Strengths & Critical Risks
### Key Strengths
${report.keyStrengths.map((s) => `- ${s}`).join('\n')}

### Critical Risks
${report.criticalRisksSummary.map((r) => `- ${r}`).join('\n')}

---

## 4. Market Demand (Google Trends)
- **Search Velocity:** ${report.demandAnalysis.growthVelocity}
- **Demand Summary:** ${report.demandAnalysis.summary}

---

## 5. Customer Pain Points (Reddit & Community)
- **Severity Score:** ${report.customerPainPoints.severityScore}/100
- **Pain Point Summary:** ${report.customerPainPoints.summary}

### Key User Complaints & Quotes
${(report.customerPainPoints.insights?.painPoints || [])
  .map((p) => `- **${p.title}** (${p.subredditOrForum}): "${p.userQuote}"`)
  .join('\n') || '- No community posts found.'}

### Hacker News YC Discussions
${report.hackerNewsAnalysis?.summary || ''}
${(report.hackerNewsAnalysis?.posts || [])
  .map((p) => `- **${p.title}** (${p.points} points, ${p.commentsCount} comments): ${p.url}`)
  .join('\n') || '- No relevant Hacker News discussions found.'}

---

## 6. Technical Ecosystem & Feasibility
- **Feasibility Score:** ${report.technicalEcosystem.feasibilityScore}/100
- **Estimated MVP Dev Time:** ${report.technicalEcosystem.insights?.estimatedDevTimeWeeks || 4} Weeks
- **Recommended Tech Stack:** ${(report.technicalEcosystem.insights?.recommendedTechStack || []).join(', ')}

---

## 7. Competitor Landscape
- **Saturation Level:** ${report.competitorLandscape.saturationLevel}
- **Market Gap Opportunity:** ${report.competitorLandscape.competitors?.gapOpportunity || 'N/A'}

### Direct Competitors
${(report.competitorLandscape.competitors?.directCompetitors || [])
  .map((c) => `- **${c.name}** (${c.pricingModel}): ${c.keyFeatures?.join(', ')}`)
  .join('\n')}

---

## 8. MVP Feature Roadmap
${report.mvpFeatures
  .map((f) => `- [${f.priority}] **${f.name}** (${f.estimatedDays} days) - ${f.description}`)
  .join('\n')}

---

## 9. Evidence Vault
${report.evidenceList
  .map((e) => `- [${e.source.toUpperCase()}] **${e.title}**: ${e.snippet} (Relevance: ${e.relevanceScore}%)`)
  .join('\n')}

---

*Report generated by Evifacto AI - Multi-Source AI Idea Validation Platform*
`;
}

export function downloadFile(content: string, fileName: string, contentType: string) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
